import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";
import Provider from "@/components/Provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>
        <div className="main">
          <div className="gradient"/>
        </div>
        <main className="flex flex-col items-center justify-center">
        <Nav/>
        {children}
        </main>
        </Provider>
      </body>
    </html>
  );
}
